### ISSUE TITLE
birthdays.yaml内にコレクション表記が混在している

### ISSUE THREAD

**Issue by ushibutatory** [ushibutatory/umamusume-birthdays#24]
こういう書き方ってどうなんだろう……？

![image](https://user-images.githubusercontent.com/15795742/115864566-fbeff980-a471-11eb-9a79-79d5fae0af3d.png)

新規キャラ追加時のメンテや差分比較が複雑なので、下記のように直したい。

```yaml
- date: ...
  names:
    - aaa
    - bbb
    - ...
```
