### ISSUE TITLE
誕生日定義の構造を変えたい

### ISSUE THREAD

**Issue by ushibutatory** [ushibutatory/umamusume-birthdays#26]
今はこうなっている。

```yaml
  - date: "03/27"
    names:
      - "オグリキャップ"
      - "エイシンフラッシュ"
      - "ゼンノロブロイ"
```

以下のようにしたい

```yaml
  - name: "オグリキャップ"
    date: "03/27"
  - name: "エイシンフラッシュ"
    date: "03/27"
  - name: "ゼンノロブロイ"
    date: "03/27"
```

日付ベースではなく、キャラベースのほうがアップデート時のキャラ追加やフィルタリングなどに対応しやすい（と思う）。
