### ISSUE TITLE
trainable.yamlのデータを更新してもDeployが走らない

### ISSUE THREAD

**Issue by ushibutatory** [ushibutatory/umamusume-birthdays#30]
```yaml
name: Deploy

on:
  push:
    branches:
      - main
    paths:
      - src/**
      - .github/workflows/Deploy.yaml
      - Dockerfile
      - birthdays.yaml
```

漏れてる。

単純にpathに追加していくのも、なんだか微妙な気がするな……。
